version: "3.9"

services:
  web:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://bircham_test_db_user:oR1OpAV8VemzojRnrXPqZcFGx2o7cg4s@dpg-d1eliqvgi27c73epi0l0-a.oregon-postgres.render.com/bircham_test_db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
